// get data home
export const GET_SUCCEEDED = 'GET_SUCCEEDED';
export const GET_FAILED = 'GET_FAILED';
export const GET_REQUEST = 'GET_REQUEST';

// get data list store

export const GET_REQUEST_STORE = 'GET_REQUEST_STORE';
export const GET_SUCCEEDED_STORE = 'GET_SUCCEEDED_STORE';
export const GET_FAILED_STORE = 'GET_FAILED_STORE';

// get data product suggest

export const GET_REQUEST_PRODUCT_SUGGEST = 'GET_REQUEST_PRODUCT_SUGGEST';
export const GET_SUCCEEDED_PRODUCT_SUGGEST = 'GET_SUCCEEDED_PRODUCT_SUGGEST';
export const GET_FAILED_PRODUCT_SUGGEST = 'GET_FAILED_PRODUCT_SUGGEST';


// get data new product

export const GET_SUCCEEDED_NEW_PRODUCT = 'GET_SUCCEEDED_NEW_PRODUCT';
export const GET_FAILED_NEW_PRODUCT = 'GET_FAILED_NEW_PRODUCT';
export const GET_REQUEST_NEW_PRODUCT = 'GET_REQUEST_NEW_PRODUCT';

// get data info product

export const GET_REQUEST_PRODUCT_INFO = 'GET_REQUEST_PRODUCT_INFO';
export const GET_SUCCEEDED_PRODUCT_INFO = 'GET_SUCCEEDED_PRODUCT_INFO';
export const GET_FAILED_PRODUCT_INFO = 'GET_FAILED_PRODUCT_INFO';

// get data info store

export const GET_REQUEST_STORE_INFO = 'GET_REQUEST_STORE_INFO';
export const GET_SUCCEEDED_STORE_INFO = 'GET_SUCCEEDED_STORE_INFO';
export const GET_FAILED_STORE_INFO = 'GET_FAILED_STORE_INFO';

// modal buy product

export const SHOW_MODAL_BUY_PRODUCT = 'SHOW_MODAL_BUY_PRODUCT';
export const HIDE_MODAL_BUY_PRODUCT = 'HIDE_MODAL_BUY_PRODUCT';

//get data tab product

export const TabProduct = {

    GET_SUCCEEDED_SELLING_PRODUCT: 'GET_SUCCEEDED_SELLING_PRODUCT',
    GET_FAILED_SELLING_PRODUCT: 'GET_FAILED_SELLING_PRODUCT',
    GET_REQUEST_SELLING_PRODUCT: 'GET_REQUEST_SELLING_PRODUCT',

    GET_SUCCEEDED_PREPARE_SELLING_PRODUCT: 'GET_SUCCEEDED_PREPARE_SELLING_PRODUCT',
    GET_FAILED_PREPARE_SELLING_PRODUCT: 'GET_FAILED_PREPARE_SELLING_PRODUCT',
    GET_REQUEST_PREPARE_SELLING_PRODUCT: 'GET_REQUEST_PREPARE_SELLING_PRODUCT',

    GET_SUCCEEDED_FAVORITE_PRODUCT: 'GET_SUCCEEDED_FAVORITE_PRODUCT',
    GET_FAILED_FAVORITE_PRODUCT: 'GET_FAILED_FAVORITE_PRODUCT',
    GET_REQUEST_FAVORITE_PRODUCT: 'GET_REQUEST_FAVORITE_PRODUCT',
};

//get data list profuct of store

export const GET_REQUEST_PRODUCT_STORE = 'GET_REQUEST_PRODUCT_STORE';
export const GET_SUCCEEDED_PRODUCT_STORE = 'GET_SUCCEEDED_PRODUCT_STORE';
export const GET_FAILED_PRODUCT_STORE = 'GET_FAILED_PRODUCT_STORE';

// get data tab store

export const TabStore = {

    GET_REQUEST_STORE_FOLLOW: 'GET_REQUEST_STORE_FOLLOW',
    GET_SUCCEEDED_STORE_FOLLOW: 'GET_SUCCEEDED_STORE_FOLLOW',
    GET_FAILED_STORE_FOLLOW: 'GET_FAILED_STORE_FOLLOW',

    GET_REQUEST_STORE_SUGGEST: 'GET_REQUEST_STORE_SUGGEST',
    GET_SUCCEEDED_STORE_SUGGEST: 'GET_SUCCEEDED_STORE_SUGGEST',
    GET_FAILED_STORE_SUGGEST: 'GET_FAILED_STORE_SUGGEST',

};

export const carts = {

    GET_CART: 'GET_CART',
    GET_CART_SUCCEEDED: 'GET_CART_SUCCEEDED',
    GET_CART_FAILED: 'GET_CART_FAILED',

    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_CART_SUCCEEDED: 'ADD_TO_CART_SUCCEEDED',
    ADD_TO_CART_FAILED: 'ADD_TO_CART_FAILED'
};

